version: '3.8'
services:
  db:
    restart: always
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    restart: always
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate && 
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings

  redis:
    restart: always
    image: "redis:alpine"

volumes:
  postgres_data:
