# Generated by Django 4.2.6 on 2023-10-31 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_remove_answer_answer_text_alter_poll_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 31, 16, 49, 43, 193124, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date published",
            ),
        ),
    ]
