# Generated by Django 4.2.6 on 2023-11-03 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0006_poll_slug_alter_poll_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 3, 13, 33, 59, 212676, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date published",
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
